# Generated by scripts/homebrew-formula.py from release archives.
class Co < Formula
  desc "Human command-line client for co.codes"
  homepage "https://co.codes"
  version "0.7.0"
  license any_of: ["MIT", "Apache-2.0"]
  depends_on "git"

  on_macos do
    on_arm do
      url "https://github.com/codotcodes/co/releases/download/v0.7.0/co-aarch64-apple-darwin.tar.gz"
      sha256 "6783ab13fcc201da794b3a760b22a8790cf071b3b1f072bbdaa5d84690c8a5e1"
    end
    on_intel do
      url "https://github.com/codotcodes/co/releases/download/v0.7.0/co-x86_64-apple-darwin.tar.gz"
      sha256 "524b12e4e74ae9348a3e934a652f9a50d2b49fd33044f89d99dc6bdb6f3273d9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/codotcodes/co/releases/download/v0.7.0/co-aarch64-unknown-linux-musl.tar.gz"
      sha256 "db2ccb19bc82b1a823a4cdc54373fbc257753b7841c54a66bf5fad9cf9c4fbb9"
    end
    on_intel do
      url "https://github.com/codotcodes/co/releases/download/v0.7.0/co-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3941b1e30c5567ec0235a55d6ff709e850901c96e8fba69a829da56b4efb9039"
    end
  end

  def install
    bin.install "co"
  end

  test do
    assert_equal "co #{version}", shell_output("#{bin}/co version").strip
  end
end
