# Generated by scripts/homebrew-formula.py from release archives.
class Co < Formula
  desc "Human command-line client for co.codes"
  homepage "https://co.codes"
  version "0.6.0"
  license any_of: ["MIT", "Apache-2.0"]
  depends_on "git"

  on_macos do
    on_arm do
      url "https://github.com/codotcodes/co/releases/download/v0.6.0/co-aarch64-apple-darwin.tar.gz"
      sha256 "169792ebba56ba9f13b03f43720db7a8bbf286bc216a4b87b25896e817746779"
    end
    on_intel do
      url "https://github.com/codotcodes/co/releases/download/v0.6.0/co-x86_64-apple-darwin.tar.gz"
      sha256 "3c0670887be0dcc69529640d454762f42e0fdcdacdf2aac62fc3e9503096a30b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/codotcodes/co/releases/download/v0.6.0/co-aarch64-unknown-linux-musl.tar.gz"
      sha256 "de155f0d14eca6d9795b7f18a09c5cd08b3411d1aea4503331ef2fa7675ee39f"
    end
    on_intel do
      url "https://github.com/codotcodes/co/releases/download/v0.6.0/co-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8bb7a1bc76397639fbb135de07036c8fb958e6c1c5602ca8f77aab916e5bd397"
    end
  end

  def install
    bin.install "co"
  end

  test do
    assert_equal "co #{version}", shell_output("#{bin}/co version").strip
  end
end
